apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hotel-ingress-stable
  namespace: hotel
spec:
  rules:
  - host: hotel.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: hotel-svc-stable
          servicePort: 80